name: fleetime_hris
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  awesome_dialog: ^3.0.2
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  currency_text_input_formatter: ^2.1.9
  day_night_time_picker: ^1.2.0+2
  dotted_border: ^2.0.0+3
  flex_color_scheme: ^7.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_form_builder: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^3.1.0
  form_builder_image_picker: ^3.2.0
  form_builder_validators: ^8.5.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  google_fonts: ^4.0.4
  image_picker: ^0.8.7+4
  intl: ^0.17.0
  loader_overlay: ^2.2.0
  modal_bottom_sheet: ^3.0.0-pre
  responsive_framework: ^1.0.0
  shimmer: ^2.0.0

dependency_overrides:
  intl: ^0.18.0

dev_dependencies:
  build_runner: null
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
